---
abstract: 'An RDF Framework for Perl'
author:
  - 'Gregory Todd Williams  C<< <gwilliams@cpan.org> >>'
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::JSON: 0
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Trine
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  DBD::SQLite: 1.14
  DBI: 0
  Data::UUID: 0
  Digest::MD5: 0
  Digest::SHA1: 0
  Error: 0
  HTTP::Negotiate: 0
  JSON: 2
  LWP::UserAgent: 0
  List::MoreUtils: 0
  List::Util: 0
  Log::Log4perl: 0
  Math::BigInt: 0
  Math::Combinatorics: 0.09
  Scalar::Util: 0
  Set::Scalar: 0
  Storable: 0
  Text::CSV: 0
  Text::Table: 0
  Time::HiRes: 0
  URI: 0
  Unicode::Escape: 0
  Unicode::String: 2.09
  XML::CommonNS: 0.04
  XML::LibXML: 1.7
  XML::Namespace: 0
  XML::SAX: 0
resources:
  homepage: http://search.cpan.org/dist/RDF-Trine/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/kasei/perlrdf/
version: 0.127_02
